name: Trivy Scan

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  trivy-scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan for vulnerabilities in dependencies (FS scan)
        run: |
          trivy fs . --exit-code 1 --severity HIGH,CRITICAL --skip-dirs node_modules

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Scan Docker image
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL my-app
